DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER(
    CUSTOMER_ID BIGINT NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    LOAN_AMOUNT NUMBER(10,2) NOT NULL,
    INTEREST NUMBER(5,2) NOT NULL,
    YEARS INTEGER NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);
